###
POST http://localhost:3000/location HTTP/1.1
Content-Type: application/json

{
    "iduser":1,
    "idcourt": 2,
    "idpayment": 1,
    "date": "2024-12-12"
}

###
GET http://localhost:3000/location HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/location/2 HTTP/1.1
Content-Type: application/json

{
    "iduser":9,
    "idcourt": 5,
    "date": "2024-12-12"
}

###
DELETE http://localhost:3000/location/2 HTTP/1.1
Content-Type: application/json





