###
POST http://localhost:3001/location/create HTTP/1.1
Content-Type: application/json

{
    "iduser":1,
    "idcourt": 2,
    "date": "2025-12-12"
}

###
GET http://localhost:3001/location/read HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3001/location/read?iduser=1 HTTP/1.1
Content-Type: application/json

###
GET  http://localhost:3001/location/show/1 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3001/location/update/2 HTTP/1.1
Content-Type: application/json

{
    "iduser":9,
    "idcourt": 5,
    "date": "2024-12-12"
}

###
DELETE http://localhost:3001/location/del/1 HTTP/1.1
Content-Type: application/json





