###
POST http://localhost:3000/payment/create HTTP/1.1
Content-Type: application/json

{     
        "method": "method",
        "total": 100,
        "date": "2024-12-12" ,
        "iduser": 1 ,
        "idlocation": 2
}

###
GET http://localhost:3000/payment/read HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/payment/read?name=Paulo HTTP/1.1
Content-Type: application/json


###
GET http://localhost:3000/payment/show/2 HTTP/1.1
Content-Type: application/json


###
DELETE http://localhost:3000/payment/del/3 HTTP/1.1
Content-Type: application/json

