###
POST http://localhost:3001/quadra/create HTTP/1.1
Content-Type: application/json

{
        "publicplace": "publicplace",
        "zipcode": "zipcode",
        "photos": "photos",
        "type": "type",
        "name": "name",
        "state": "state",
        "city": "city",
        "neighborhood": "neighborhood",
        "preco": "R$150,00",
        "alugado": "alugado",
        "naoalugado": "naoalugado"
}

###
GET http://localhost:3001/quadra/read HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/quadra/read?name=Juan HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/quadra/show/4 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/quadra/update/4 HTTP/1.1
Content-Type: application/json

{
       "publicplace": "Rua Sem volta",
        "zipcode": "12345-345",
        "photos": "photos",
        "type": "quadra1",
        "name": "Juan",
        "state": "SP",
        "city": "São Carlos",
        "neighborhood": "Santa Paula", 
        "alugado": "Alugado"
}

###
DELETE http://localhost:3000/quadra/del/4 HTTP/1.1
Content-Type: application/json


