
### criar um user
POST http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
    "name":"Paulo", 
    "pass":"Senac@123",
    "cpf": "553536732",
    "email": "rafaelazumiyoung@gmail.com",
    "phone": "16 992823571",
    "type": "admin"
    
}



### lista os usuario
GET http://localhost:3000/user/read HTTP/1.1
Content-Type: application/json

### lista os usuario
GET http://localhost:3000/user/show/2 HTTP/1.1
Content-Type: application/json


### editar um user
PUT http://localhost:3000/user/update/1 HTTP/1.1
Content-Type: application/json

{
    "name":"Paulo", 
    "pass":"3@123",
    "cpf": "8987979765756",
    "email": "rafaela567zumiyoung@gmail.com",
    "phone": "16 992823571",
    "type": "admin2"
}

###
DELETE http://localhost:3000/user/del/1  HTTP/1.1
Content-Type: application/json
